// S2 · extra · ficha 17 · quais dos 4 numeros sao divisiveis por 2 e por 3
inicio
    inteiro n1, n2, n3, n4

    escrever "Numero 1: "
    ler n1
    escrever "Numero 2: "
    ler n2
    escrever "Numero 3: "
    ler n3
    escrever "Numero 4: "
    ler n4

    escrever "Divisiveis por 2 e por 3: "
    se n1 % 2 = 0 e n1 % 3 = 0 entao
        escrever n1, " "
    fimse
    se n2 % 2 = 0 e n2 % 3 = 0 entao
        escrever n2, " "
    fimse
    se n3 % 2 = 0 e n3 % 3 = 0 entao
        escrever n3, " "
    fimse
    se n4 % 2 = 0 e n4 % 3 = 0 entao
        escrever n4, " "
    fimse
fim
