// S3 · snippet 2 · operadores aritmeticos
inicio
    inteiro a <- 7, b <- 2
    real r

    escrever "a + b = ", a + b, "\n"
    escrever "a - b = ", a - b, "\n"
    escrever "a * b = ", a * b, "\n"
    escrever "a / b = ", a / b, "\n"
    escrever "a % b = ", a % b, "\n"
    escrever "a ^ b = ", a ^ b, "\n"

    r <- a / b
    escrever "r <- a / b da ", r, "\n"
    r <- a / 2.0
    escrever "r <- a / 2.0 da ", r
fim
