
inicio
    //entradas
	inteiro largura, altura, area, perimetro
    
    // pedir dados para calcular (larg e alt)
    escrever "Largura (m): "
    ler largura
    escrever "Altura (m): "
    ler altura
    
    // sequencia logica, calcular area e perimetro
    area <- largura * altura
    perimetro <- 2 * (altura + largura)
    
    // saidas escrever no ecra
    escrever "Area: ", area , "m2\n"
    escrever "Perimetro: ", perimetro , "m\n"
    
fim
