// S3 · extra · ficha 18 · divisiveis por 2 ou por 3
inicio
    inteiro a, b, c, d

    escrever "Quatro numeros inteiros:\n"
    ler a
    ler b
    ler c
    ler d

    escrever "Divisiveis por 2 ou por 3: "
    se a % 2 = 0 ou a % 3 = 0 entao
        escrever a, " "
    fimse
    se b % 2 = 0 ou b % 3 = 0 entao
        escrever b, " "
    fimse
    se c % 2 = 0 ou c % 3 = 0 entao
        escrever c, " "
    fimse
    se d % 2 = 0 ou d % 3 = 0 entao
        escrever d, " "
    fimse
fim
